export type JsonSchema = Readonly<Record<string, unknown>>;

const uuidV7Pattern = '[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}';
const idPattern = `^[a-z]{3}_${uuidV7Pattern}$`;
const hashPattern = '^sha256:[0-9a-f]{64}$';
const hashDigestPattern = 'sha256:[0-9a-f]{64}';
const shaPattern = '^(?:[0-9a-f]{40}|[0-9a-f]{64})$';
const repoPattern = '^(?:github:[1-9][0-9]*|local:sha256:[0-9a-f]{64})$';
const pathPattern =
  '^(?!/)(?![A-Za-z]:)(?!.*(?:^|/)\\.{1,2}(?:/|$))(?!.*//)(?!.*\\\\)(?!.*\\u0000).+(?<!/)$';

export const valueTypesSchema = {
  $schema: 'https://json-schema.org/draft/2020-12/schema',
  $id: 'https://schemas.yanibhq.dev/reverb/value-types/v1.json',
  title: 'Reverb foundation value types',
  $defs: {
    opaqueId: { type: 'string', pattern: idPattern },
    contentHash: { type: 'string', pattern: hashPattern },
    commitSha: { type: 'string', pattern: shaPattern },
    repositoryStableId: { type: 'string', pattern: repoPattern },
    repoPath: { type: 'string', pattern: pathPattern },
    instant: { type: 'string', pattern: '^\\d{4}-\\d{2}-\\d{2}T.*Z$' },
  },
} as const satisfies JsonSchema;

export const coverageRecordSchema = {
  $schema: 'https://json-schema.org/draft/2020-12/schema',
  $id: 'https://schemas.yanibhq.dev/reverb/coverage-record/v1.json',
  title: 'Reverb coverage record',
  type: 'object',
  additionalProperties: false,
  required: ['dimension', 'state', 'eligible', 'processed', 'skipped', 'failed'],
  properties: {
    dimension: { enum: ['repository', 'tree', 'file', 'language', 'parser', 'adapter'] },
    state: { enum: ['complete', 'partial', 'failed', 'unauthorized', 'not_analysed'] },
    eligible: { type: 'integer', minimum: 0 },
    processed: { type: 'integer', minimum: 0 },
    skipped: { type: 'integer', minimum: 0 },
    failed: { type: 'integer', minimum: 0 },
    reason: { type: 'string' },
    scope: { type: 'string', pattern: pathPattern },
  },
} as const satisfies JsonSchema;

export const repositoryGenerationSchema = {
  $schema: 'https://json-schema.org/draft/2020-12/schema',
  $id: 'https://schemas.yanibhq.dev/reverb/repository-generation/v1.json',
  title: 'Reverb repository generation',
  type: 'object',
  additionalProperties: false,
  required: [
    'schema',
    'schema_version',
    'id',
    'workspace_id',
    'repository_id',
    'commit_sha',
    'tree_hash',
    'indexer_bundle_version',
    'config_revision',
    'registry_revision',
    'state',
    'started_at',
    'selectable',
  ],
  properties: {
    schema: { const: 'reverb.repository-generation' },
    schema_version: { const: '1.0' },
    id: { type: 'string', pattern: `^gen_${uuidV7Pattern}$` },
    workspace_id: { type: 'string', pattern: `^wsp_${uuidV7Pattern}$` },
    repository_id: { type: 'string', pattern: repoPattern },
    commit_sha: { type: 'string', pattern: shaPattern },
    tree_hash: { type: 'string', pattern: shaPattern },
    indexer_bundle_version: { type: 'string', minLength: 1, maxLength: 128 },
    config_revision: { type: 'string', pattern: `^cfg_${hashDigestPattern}$` },
    registry_revision: { type: 'string', pattern: `^reg_${hashDigestPattern}$` },
    state: { enum: ['building', 'complete', 'partial', 'failed', 'expired'] },
    started_at: { type: 'string', pattern: '^\\d{4}-\\d{2}-\\d{2}T.*Z$' },
    completed_at: { type: 'string', pattern: '^\\d{4}-\\d{2}-\\d{2}T.*Z$' },
    coverage_hash: { type: 'string', pattern: hashPattern },
    artifact_result_hash: { type: 'string', pattern: hashPattern },
    selectable: { type: 'boolean' },
    derivation: {
      type: 'object',
      additionalProperties: false,
      required: ['base_generation_id', 'overlay_id', 'storage_mode'],
      properties: {
        base_generation_id: { type: 'string', pattern: `^gen_${uuidV7Pattern}$` },
        overlay_id: { type: 'string', pattern: `^ovl_${uuidV7Pattern}$` },
        storage_mode: { const: 'base_overlay' },
      },
    },
  },
} as const satisfies JsonSchema;

export const overlaySchema = {
  $schema: 'https://json-schema.org/draft/2020-12/schema',
  $id: 'https://schemas.yanibhq.dev/reverb/pull-request-overlay/v1.json',
  title: 'Reverb pull request overlay',
  type: 'object',
  additionalProperties: false,
  required: [
    'schema',
    'schema_version',
    'id',
    'workspace_id',
    'repository_id',
    'base_generation_id',
    'base_sha',
    'head_sha',
    'head_tree_hash',
    'indexer_bundle_version',
    'config_revision',
    'registry_revision',
    'state',
    'supersession_key',
    'diff_hash',
    'started_at',
  ],
  properties: {
    schema: { const: 'reverb.pull-request-overlay' },
    schema_version: { const: '1.0' },
    id: { type: 'string', pattern: `^ovl_${uuidV7Pattern}$` },
    workspace_id: { type: 'string', pattern: `^wsp_${uuidV7Pattern}$` },
    repository_id: { type: 'string', pattern: repoPattern },
    base_generation_id: { type: 'string', pattern: `^gen_${uuidV7Pattern}$` },
    base_sha: { type: 'string', pattern: shaPattern },
    head_sha: { type: 'string', pattern: shaPattern },
    head_tree_hash: { type: 'string', pattern: shaPattern },
    indexer_bundle_version: { type: 'string', minLength: 1, maxLength: 128 },
    config_revision: { type: 'string', pattern: `^cfg_${hashDigestPattern}$` },
    registry_revision: { type: 'string', pattern: `^reg_${hashDigestPattern}$` },
    state: { enum: ['building', 'complete', 'partial', 'failed'] },
    supersession_key: { type: 'string', pattern: hashPattern },
    diff_hash: { type: 'string', pattern: hashPattern },
    result_hash: { type: 'string', pattern: hashPattern },
    started_at: { type: 'string', pattern: '^\\d{4}-\\d{2}-\\d{2}T.*Z$' },
    completed_at: { type: 'string', pattern: '^\\d{4}-\\d{2}-\\d{2}T.*Z$' },
  },
} as const satisfies JsonSchema;

export const registrySnapshotSchema = {
  $schema: 'https://json-schema.org/draft/2020-12/schema',
  $id: 'https://schemas.yanibhq.dev/reverb/workspace-registry/v1.json',
  title: 'Reverb workspace registry',
  type: 'object',
  additionalProperties: true,
  required: ['schema', 'schema_version', 'workspace', 'revision', 'repositories'],
  properties: {
    schema: { const: 'reverb.workspace-registry' },
    schema_version: { const: '1.0' },
    workspace: {
      type: 'object',
      additionalProperties: true,
      required: ['id'],
      properties: { id: { type: 'string', pattern: `^wsp_${uuidV7Pattern}$` } },
    },
    revision: {
      type: 'object',
      additionalProperties: true,
      required: ['sequence', 'id', 'created_at', 'created_by', 'source', 'reason'],
      properties: {
        sequence: { type: 'integer', minimum: 1 },
        id: { type: 'string', pattern: `^reg_${hashDigestPattern}$` },
        created_at: { type: 'string', pattern: '^\\d{4}-\\d{2}-\\d{2}T.*Z$' },
        created_by: { type: 'string', minLength: 1 },
        source: { type: 'string', minLength: 1 },
        reason: { type: 'string', minLength: 1 },
      },
    },
    repositories: { type: 'array', items: { type: 'object' } },
    services: { type: 'array', items: { type: 'object' } },
    aliases: { type: 'array', items: { type: 'object' } },
    consents: { type: 'array', items: { type: 'object' } },
  },
} as const satisfies JsonSchema;

export const adapterManifestSchema = {
  $schema: 'https://json-schema.org/draft/2020-12/schema',
  $id: 'https://schemas.yanibhq.dev/reverb/adapter-manifest/v1.json',
  title: 'Reverb adapter manifest',
  type: 'object',
  additionalProperties: false,
  required: [
    'schema',
    'schema_version',
    'id',
    'version',
    'identity_version',
    'contract_kinds',
    'capability_tiers',
    'evidence_strata',
    'external_tools',
    'limitations',
    'resource_budget',
    'maintainer',
  ],
  properties: {
    schema: { const: 'reverb.adapter-manifest' },
    schema_version: { const: '1.0' },
    id: { type: 'string', pattern: '^[a-z][a-z0-9]*(?:[.-][a-z0-9]+)+$' },
    version: {
      type: 'string',
      pattern: '^(?:0|[1-9]\\d*)\\.(?:0|[1-9]\\d*)\\.(?:0|[1-9]\\d*)(?:-[0-9A-Za-z.-]+)?$',
    },
    identity_version: { type: 'integer', minimum: 1 },
    contract_kinds: {
      type: 'array',
      minItems: 1,
      uniqueItems: true,
      items: {
        enum: ['typescript_symbol', 'openapi_operation', 'protobuf_method', 'protobuf_field'],
      },
    },
    capability_tiers: { type: 'array', minItems: 1, items: { type: 'object' } },
    evidence_strata: { type: 'array', minItems: 1, items: { type: 'object' } },
    external_tools: { type: 'array', items: { type: 'object' } },
    limitations: { type: 'array', items: { type: 'string', minLength: 1, maxLength: 512 } },
    resource_budget: {
      type: 'object',
      additionalProperties: false,
      required: [
        'timeout_ms',
        'memory_mib',
        'maximum_input_bytes',
        'maximum_output_bytes',
        'maximum_items',
      ],
      properties: {
        timeout_ms: { type: 'integer', minimum: 1 },
        memory_mib: { type: 'integer', minimum: 1 },
        maximum_input_bytes: { type: 'integer', minimum: 1 },
        maximum_output_bytes: { type: 'integer', minimum: 1 },
        maximum_items: { type: 'integer', minimum: 1 },
      },
    },
    maintainer: { type: 'string', minLength: 1, maxLength: 256 },
    deprecated: { type: 'object' },
  },
} as const satisfies JsonSchema;

export const adapterExtractionSchema = {
  $schema: 'https://json-schema.org/draft/2020-12/schema',
  $id: 'https://schemas.yanibhq.dev/reverb/adapter-extraction/v1.json',
  title: 'Reverb adapter extraction result',
  type: 'object',
  additionalProperties: false,
  required: [
    'schema',
    'schema_version',
    'adapter_id',
    'adapter_version',
    'identity_version',
    'config_revision',
    'definitions',
    'references',
    'coverage',
    'diagnostics',
    'source_fingerprint',
    'output_hash',
  ],
  properties: {
    schema: { const: 'reverb.adapter-extraction' },
    schema_version: { const: '1.0' },
    adapter_id: { type: 'string', pattern: '^[a-z][a-z0-9]*(?:[.-][a-z0-9]+)+$' },
    adapter_version: { type: 'string', minLength: 1 },
    identity_version: { type: 'integer', minimum: 1 },
    config_revision: { type: 'string', pattern: `^cfg_${hashDigestPattern}$` },
    definitions: { type: 'array', items: { type: 'object' } },
    references: { type: 'array', items: { type: 'object' } },
    coverage: { type: 'object' },
    diagnostics: { type: 'array', items: { type: 'object' } },
    source_fingerprint: { type: 'string', pattern: hashPattern },
    output_hash: { type: 'string', pattern: hashPattern },
  },
} as const satisfies JsonSchema;

export const evidenceEdgeSchema = {
  $schema: 'https://json-schema.org/draft/2020-12/schema',
  $id: 'https://schemas.yanibhq.dev/reverb/evidence-edge/v1.json',
  title: 'Reverb temporal evidence edge',
  type: 'object',
  additionalProperties: false,
  required: [
    'schema',
    'schema_version',
    'id',
    'workspace_id',
    'producer_repository_id',
    'consumer_repository_id',
    'producer_generation_id',
    'consumer_generation_id',
    'contract_kind',
    'definition_key',
    'stable_reference_id',
    'basis',
    'primary_path',
    'stratum_key',
    'registry_revision',
    'first_observed_at',
    'last_observed_at',
    'definition',
    'reference',
  ],
  properties: {
    schema: { const: 'reverb.evidence-edge' },
    schema_version: { const: '1.0' },
    id: { type: 'string', pattern: `^edg_${hashDigestPattern}$` },
    workspace_id: { type: 'string', pattern: `^wsp_${uuidV7Pattern}$` },
    producer_repository_id: { type: 'string', pattern: repoPattern },
    consumer_repository_id: { type: 'string', pattern: repoPattern },
    producer_generation_id: { type: 'string', pattern: `^gen_${uuidV7Pattern}$` },
    consumer_generation_id: { type: 'string', pattern: `^gen_${uuidV7Pattern}$` },
    contract_kind: {
      enum: ['typescript_symbol', 'openapi_operation', 'protobuf_method', 'protobuf_field'],
    },
    definition_key: { type: 'string', minLength: 1 },
    stable_reference_id: { type: 'string', pattern: `^ref_${hashDigestPattern}$` },
    basis: {
      enum: ['exact', 'registry_resolved', 'heuristic', 'declared_context', 'behavioural_context'],
    },
    primary_path: { type: 'object' },
    stratum_key: { type: 'string', minLength: 1 },
    registry_revision: { type: 'string', pattern: `^reg_${hashDigestPattern}$` },
    first_observed_at: { type: 'string', pattern: '^\\d{4}-\\d{2}-\\d{2}T.*Z$' },
    last_observed_at: { type: 'string', pattern: '^\\d{4}-\\d{2}-\\d{2}T.*Z$' },
    invalidated_at: { type: 'string', pattern: '^\\d{4}-\\d{2}-\\d{2}T.*Z$' },
    invalidation_reason: {
      enum: ['complete_reference_absence', 'registry_revision_changed', 'membership_removed'],
    },
    definition: { type: 'object' },
    reference: { type: 'object' },
  },
} as const satisfies JsonSchema;

export const analysisResultSchema = {
  $schema: 'https://json-schema.org/draft/2020-12/schema',
  $id: 'https://schemas.yanibhq.dev/reverb/analysis-result/v1.json',
  title: 'Reverb canonical analysis result',
  type: 'object',
  additionalProperties: false,
  required: [
    'schema',
    'schema_version',
    'analysis_id',
    'workspace_id',
    'producer_repository_id',
    'pull_request',
    'registry_revision',
    'policy_revision',
    'policy_major',
    'state',
    'current',
    'consumers',
    'findings',
    'abstentions',
    'started_at',
    'completed_at',
    'output_hash',
  ],
  properties: {
    schema: { const: 'reverb.analysis-result' },
    schema_version: { const: '1.0' },
    analysis_id: { type: 'string', pattern: `^ana_${uuidV7Pattern}$` },
    workspace_id: { type: 'string', pattern: `^wsp_${uuidV7Pattern}$` },
    producer_repository_id: { type: 'string', pattern: repoPattern },
    pull_request: {
      type: 'object',
      additionalProperties: false,
      required: ['provider', 'base_sha', 'head_sha'],
      properties: {
        provider: { enum: ['local', 'github'] },
        number: { type: 'integer', minimum: 1 },
        base_sha: { type: 'string', pattern: shaPattern },
        head_sha: { type: 'string', pattern: shaPattern },
      },
    },
    registry_revision: { type: 'string', pattern: `^reg_${hashDigestPattern}$` },
    policy_revision: { type: 'string', pattern: `^pol_${hashDigestPattern}$` },
    policy_major: { type: 'integer', minimum: 1 },
    state: { enum: ['complete', 'partial', 'superseded', 'not_analysed'] },
    current: { type: 'boolean' },
    consumers: { type: 'array', items: { type: 'object' } },
    findings: { type: 'array', items: { type: 'object' } },
    abstentions: { type: 'array', items: { type: 'object' } },
    started_at: { type: 'string', pattern: '^\\d{4}-\\d{2}-\\d{2}T.*Z$' },
    completed_at: { type: 'string', pattern: '^\\d{4}-\\d{2}-\\d{2}T.*Z$' },
    output_hash: { type: 'string', pattern: hashPattern },
  },
} as const satisfies JsonSchema;

const edgeLabels = ['confirmed', 'absent', 'indeterminate'] as const;
const impactLabels = ['breaking', 'behavior_risk', 'compatible', 'indeterminate'] as const;
const actionLabels = [
  'coordinate',
  'already_coordinated',
  'accepted_risk',
  'dead_or_test_only',
  'no_action',
  'indeterminate',
] as const;

export const reviewEventSchema = {
  $schema: 'https://json-schema.org/draft/2020-12/schema',
  $id: 'https://schemas.yanibhq.dev/reverb/review-event/v1.json',
  title: 'Reverb append-only review event',
  type: 'object',
  additionalProperties: false,
  required: [
    'schema',
    'schema_version',
    'id',
    'workspace_id',
    'finding_occurrence_id',
    'finding_fingerprint',
    'actor',
    'authorization',
    'occurred_at',
    'versions',
    'labels',
    'reason',
    'note_hash',
    'output_hash',
  ],
  properties: {
    schema: { const: 'reverb.review-event' },
    schema_version: { const: '1.0' },
    id: { type: 'string', pattern: `^rev_${uuidV7Pattern}$` },
    workspace_id: { type: 'string', pattern: `^wsp_${uuidV7Pattern}$` },
    finding_occurrence_id: { type: 'string', pattern: `^occ_${hashDigestPattern}$` },
    finding_fingerprint: { type: 'string', pattern: `^fnd_${hashDigestPattern}$` },
    actor: {
      type: 'object',
      additionalProperties: false,
      required: ['id', 'role', 'domain_capability', 'detector_author_conflict'],
      properties: {
        id: { type: 'string', minLength: 1 },
        role: { enum: ['reviewer', 'repository_owner', 'workspace_admin'] },
        domain_capability: { type: 'string', minLength: 1 },
        detector_author_conflict: { type: 'boolean' },
      },
    },
    authorization: {
      type: 'object',
      additionalProperties: false,
      required: ['revision', 'authorized_at', 'permission'],
      properties: {
        revision: { type: 'string', pattern: `^reg_${hashDigestPattern}$` },
        authorized_at: { type: 'string', pattern: '^\\d{4}-\\d{2}-\\d{2}T.*Z$' },
        permission: { const: 'finding.review' },
      },
    },
    occurred_at: { type: 'string', pattern: '^\\d{4}-\\d{2}-\\d{2}T.*Z$' },
    versions: { type: 'object' },
    labels: {
      type: 'object',
      additionalProperties: false,
      required: ['edge', 'impact', 'action'],
      properties: {
        edge: { enum: edgeLabels },
        impact: { enum: impactLabels },
        action: { enum: actionLabels },
      },
    },
    reason: { type: 'string', minLength: 1 },
    note_hash: { type: 'string', pattern: hashPattern },
    supersedes: { type: 'string', pattern: `^rev_${uuidV7Pattern}$` },
    suppression_rule_id: { type: 'string', pattern: `^sup_${hashDigestPattern}$` },
    output_hash: { type: 'string', pattern: hashPattern },
  },
} as const satisfies JsonSchema;

export const suppressionRuleSchema = {
  $schema: 'https://json-schema.org/draft/2020-12/schema',
  $id: 'https://schemas.yanibhq.dev/reverb/suppression-rule/v1.json',
  title: 'Reverb structurally invalidated suppression rule',
  type: 'object',
  additionalProperties: false,
  required: [
    'schema',
    'schema_version',
    'id',
    'workspace_id',
    'matcher',
    'owner',
    'justification',
    'justification_hash',
    'created_at',
    'review_at',
    'expires_at',
    'invalidation_predicates',
    'initial_state',
    'output_hash',
  ],
  properties: {
    schema: { const: 'reverb.suppression-rule' },
    schema_version: { const: '1.0' },
    id: { type: 'string', pattern: `^sup_${hashDigestPattern}$` },
    workspace_id: { type: 'string', pattern: `^wsp_${uuidV7Pattern}$` },
    matcher: {
      type: 'object',
      required: ['scope'],
      properties: {
        scope: {
          enum: [
            'occurrence',
            'stable_finding',
            'contract_consumer',
            'repository_pair_kind',
            'adapter_rule',
            'workspace_rule',
          ],
        },
      },
    },
    owner: {
      type: 'object',
      additionalProperties: false,
      required: ['actor_id', 'role', 'authorization_revision'],
      properties: {
        actor_id: { type: 'string', minLength: 1 },
        role: { enum: ['reviewer', 'repository_owner', 'workspace_admin'] },
        authorization_revision: { type: 'string', pattern: `^reg_${hashDigestPattern}$` },
      },
    },
    justification: { type: 'string', minLength: 8, maxLength: 2000 },
    justification_hash: { type: 'string', pattern: hashPattern },
    created_at: { type: 'string', pattern: '^\\d{4}-\\d{2}-\\d{2}T.*Z$' },
    review_at: { type: 'string', pattern: '^\\d{4}-\\d{2}-\\d{2}T.*Z$' },
    expires_at: { type: 'string', pattern: '^\\d{4}-\\d{2}-\\d{2}T.*Z$' },
    invalidation_predicates: {
      type: 'array',
      minItems: 1,
      items: {
        type: 'object',
        required: ['kind'],
        properties: {
          kind: {
            enum: [
              'producer_code',
              'consumer_code',
              'consumer_reference',
              'contract_shape',
              'identity_version',
              'adapter_version',
              'evidence_stratum',
              'policy_revision',
              'registry_revision',
            ],
          },
        },
      },
    },
    initial_state: { const: 'active' },
    output_hash: { type: 'string', pattern: hashPattern },
  },
} as const satisfies JsonSchema;

export const impactCaseSchema = {
  $schema: 'https://json-schema.org/draft/2020-12/schema',
  $id: 'https://schemas.yanibhq.dev/reverb/impact-case/v1.json',
  title: 'Reverb independently sampled impact case',
  type: 'object',
  additionalProperties: false,
  required: [
    'schema',
    'schema_version',
    'id',
    'subset',
    'organization_id',
    'repository_family_id',
    'team_id',
    'eligible_pull_request_id',
    'producer_repository_id',
    'producer_base_sha',
    'producer_head_sha',
    'pull_request_opened_at',
    'consumer_repository_id',
    'consumer_sha_as_of_pull_request_open',
    'consumer_snapshot_observed_at',
    'producer_generation_id',
    'consumer_generation_id',
    'stable_consumer_reference_id',
    'contract_kind',
    'canonical_contract_key',
    'change_kind',
    'stratum',
    'adapter_versions',
    'identity_function_version',
    'registry_revision',
    'policy_revision',
    'evidence',
    'coverage',
    'detector_output',
    'analysis_outcome',
    'detector_claims',
    'policy_selected',
    'suppressed',
    'required_for_evaluation',
    'sampling',
    'releaseability',
    'evaluation_consent',
    'research_consent',
    'analysis_latency_ms',
    'cost_microunits',
    'confidentiality_defects',
    'removal_coverage_defect',
    'remedy_available',
    'output_hash',
  ],
  properties: {
    schema: { const: 'reverb.impact-case' },
    schema_version: { const: '1.0' },
    id: { type: 'string', pattern: `^cas_${hashDigestPattern}$` },
    subset: { enum: ['historical', 'executable_replay', 'mutation', 'forward_shadow'] },
    organization_id: { type: 'string', minLength: 1 },
    repository_family_id: { type: 'string', minLength: 1 },
    team_id: { type: 'string', minLength: 1 },
    eligible_pull_request_id: { type: 'string', minLength: 1 },
    producer_repository_id: { type: 'string', pattern: repoPattern },
    producer_base_sha: { type: 'string', pattern: shaPattern },
    producer_head_sha: { type: 'string', pattern: shaPattern },
    pull_request_opened_at: { type: 'string' },
    consumer_repository_id: { type: 'string', pattern: repoPattern },
    consumer_sha_as_of_pull_request_open: { type: 'string', pattern: shaPattern },
    consumer_snapshot_observed_at: { type: 'string' },
    producer_generation_id: { type: 'string', pattern: `^gen_${uuidV7Pattern}$` },
    consumer_generation_id: { type: 'string', pattern: `^gen_${uuidV7Pattern}$` },
    stable_consumer_reference_id: { type: 'string', pattern: `^ref_${hashDigestPattern}$` },
    contract_kind: {
      enum: ['typescript_symbol', 'openapi_operation', 'protobuf_method', 'protobuf_field'],
    },
    canonical_contract_key: { type: 'string', minLength: 1 },
    change_kind: { type: 'string', minLength: 1 },
    stratum: { type: 'object' },
    adapter_versions: { type: 'object' },
    identity_function_version: { type: 'string', minLength: 1 },
    registry_revision: { type: 'string', pattern: `^reg_${hashDigestPattern}$` },
    policy_revision: { type: 'string', pattern: `^pol_${hashDigestPattern}$` },
    evidence: { type: 'array', items: { type: 'object' } },
    coverage: { type: 'array', items: { type: 'object' } },
    detector_output: { enum: ['candidate', 'abstained', 'no_candidate', 'not_analysed'] },
    analysis_outcome: { enum: ['completed', 'superseded', 'timeout', 'not_analysed'] },
    detector_claims: { type: 'object' },
    policy_selected: { type: 'boolean' },
    suppressed: { type: 'boolean' },
    required_for_evaluation: { type: 'boolean' },
    labels: {
      type: 'object',
      additionalProperties: false,
      required: ['edge', 'impact', 'action'],
      properties: {
        edge: { enum: edgeLabels },
        impact: { enum: impactLabels },
        action: { enum: actionLabels },
      },
    },
    labeler_provenance: { type: 'object' },
    sampling: {
      type: 'object',
      additionalProperties: false,
      required: ['frame_source', 'inclusion_probability', 'sampling_weight', 'seed'],
      properties: {
        frame_source: { enum: ['provider_metadata', 'supported_artifact_discovery'] },
        inclusion_probability: { type: 'number', exclusiveMinimum: 0, maximum: 1 },
        sampling_weight: { type: 'number', minimum: 1 },
        seed: { type: 'string' },
      },
    },
    releaseability: {
      enum: ['public', 'private_aggregate_only', 'private_not_releasable'],
    },
    evaluation_consent: { type: 'boolean' },
    research_consent: { type: 'boolean' },
    analysis_latency_ms: { type: 'number', minimum: 0 },
    cost_microunits: { type: 'number', minimum: 0 },
    confidentiality_defects: { type: 'integer', minimum: 0 },
    removal_coverage_defect: { type: 'boolean' },
    remedy_available: { type: 'boolean' },
    action_observed: { type: 'boolean' },
    time_to_action_ms: { type: 'number', minimum: 0 },
    action_censored: { type: 'boolean' },
    output_hash: { type: 'string', pattern: hashPattern },
  },
} as const satisfies JsonSchema;

export const corpusManifestSchema = {
  $schema: 'https://json-schema.org/draft/2020-12/schema',
  $id: 'https://schemas.yanibhq.dev/reverb/corpus-manifest/v1.json',
  title: 'Reverb corpus manifest',
  type: 'object',
  additionalProperties: false,
  required: [
    'schema',
    'schema_version',
    'revision',
    'created_at',
    'handbook_version',
    'frame_source',
    'population_hash',
    'eligible_population_count',
    'case_ids',
    'subset_counts',
    'public_case_ids',
    'output_hash',
  ],
  properties: {
    schema: { const: 'reverb.corpus-manifest' },
    schema_version: { const: '1.0' },
    revision: { type: 'string', pattern: hashPattern },
    created_at: { type: 'string' },
    handbook_version: { type: 'string', minLength: 1 },
    frame_source: { enum: ['provider_metadata', 'supported_artifact_discovery'] },
    population_hash: { type: 'string', pattern: hashPattern },
    eligible_population_count: { type: 'integer', minimum: 0 },
    case_ids: {
      type: 'array',
      uniqueItems: true,
      items: { type: 'string', pattern: `^cas_${hashDigestPattern}$` },
    },
    subset_counts: { type: 'object' },
    public_case_ids: {
      type: 'array',
      uniqueItems: true,
      items: { type: 'string', pattern: `^cas_${hashDigestPattern}$` },
    },
    output_hash: { type: 'string', pattern: hashPattern },
  },
} as const satisfies JsonSchema;

function reportEnvelope(
  schemaName: string,
  id: string,
  title: string,
): JsonSchema & { readonly $id: string } {
  return {
    $schema: 'https://json-schema.org/draft/2020-12/schema',
    $id: id,
    title,
    type: 'object',
    required: ['schema', 'schema_version'],
    properties: { schema: { const: schemaName }, schema_version: { const: '1.0' } },
  };
}

export const evaluationReportSchema = reportEnvelope(
  'reverb.evaluation-report',
  'https://schemas.yanibhq.dev/reverb/evaluation-report/v1.json',
  'Reverb evaluation report',
);
export const policySimulationSchema = reportEnvelope(
  'reverb.policy-simulation',
  'https://schemas.yanibhq.dev/reverb/policy-simulation/v1.json',
  'Reverb frozen policy simulation',
);
export const promotionRecordSchema = reportEnvelope(
  'reverb.promotion-record',
  'https://schemas.yanibhq.dev/reverb/promotion-record/v1.json',
  'Reverb promotion audit record',
);

export const findingDisclosureProjectionSchema = {
  $schema: 'https://json-schema.org/draft/2020-12/schema',
  $id: 'https://schemas.yanibhq.dev/reverb/finding-disclosure-projection/v1.json',
  title: 'Reverb field-level disclosure decision',
  type: 'object',
  additionalProperties: false,
  required: [
    'schema',
    'schema_version',
    'workspace_id',
    'destination_repository_id',
    'audience',
    'registry_revision',
    'allowed',
    'omitted',
    'decision_hash',
  ],
  properties: {
    schema: { const: 'reverb.finding-disclosure-projection' },
    schema_version: { const: '1.0' },
    workspace_id: { type: 'string', pattern: `^wsp_${uuidV7Pattern}$` },
    destination_repository_id: { type: 'string', pattern: repoPattern },
    audience: { enum: ['static', 'personalized'] },
    registry_revision: { type: 'string', pattern: `^reg_${hashDigestPattern}$` },
    allowed: { type: 'object', additionalProperties: { type: 'string' } },
    omitted: {
      type: 'array',
      items: {
        type: 'object',
        additionalProperties: false,
        required: ['field', 'name', 'reason'],
        properties: {
          field: {
            enum: ['repository_identity', 'contract_identity', 'location', 'snippet'],
          },
          name: { type: 'string', minLength: 1 },
          reason: {
            enum: [
              'no_explicit_grant',
              'app_access_denied',
              'whole_audience_safety_unproven',
              'viewer_access_denied',
            ],
          },
        },
      },
    },
    decision_hash: { type: 'string', pattern: hashPattern },
  },
} as const satisfies JsonSchema;

export const githubCheckProjectionSchema = {
  $schema: 'https://json-schema.org/draft/2020-12/schema',
  $id: 'https://schemas.yanibhq.dev/reverb/github-check-projection/v1.json',
  title: 'Reverb disclosure-safe GitHub Check projection',
  type: 'object',
  additionalProperties: false,
  required: [
    'schema',
    'schema_version',
    'check_key',
    'workspace_id',
    'repository_id',
    'pull_request_number',
    'head_sha',
    'policy_revision',
    'conclusion',
    'advisory',
    'never_blocking',
    'title',
    'summary',
    'coverage',
    'findings',
    'finding_total',
    'truncated_finding_count',
    'annotations',
    'truncated_annotation_count',
    'limitations',
    'detail_url',
    'projection_hash',
  ],
  properties: {
    schema: { const: 'reverb.github-check-projection' },
    schema_version: { const: '1.0' },
    check_key: { type: 'string', pattern: hashPattern },
    workspace_id: { type: 'string', pattern: `^wsp_${uuidV7Pattern}$` },
    repository_id: { type: 'string', pattern: repoPattern },
    pull_request_number: { type: 'integer', minimum: 1 },
    head_sha: { type: 'string', pattern: shaPattern },
    policy_revision: { type: 'string', pattern: `^pol_${hashDigestPattern}$` },
    conclusion: { enum: ['success', 'neutral', 'skipped'] },
    advisory: { const: true },
    never_blocking: { const: true },
    title: { type: 'string', minLength: 1 },
    summary: { type: 'string', minLength: 1 },
    coverage: { type: 'object' },
    findings: { type: 'array', items: { type: 'object' } },
    finding_total: { type: 'integer', minimum: 0 },
    truncated_finding_count: { type: 'integer', minimum: 0 },
    annotations: { type: 'array', items: { type: 'object' }, maxItems: 50 },
    truncated_annotation_count: { type: 'integer', minimum: 0 },
    limitations: { type: 'array', items: { type: 'string' } },
    detail_url: { type: 'string', minLength: 1 },
    projection_hash: { type: 'string', pattern: hashPattern },
  },
} as const satisfies JsonSchema;

export const FOUNDATION_SCHEMAS = Object.freeze([
  { file: 'reverb-value-types.schema.json', schema: valueTypesSchema },
  { file: 'reverb-coverage-record.schema.json', schema: coverageRecordSchema },
  { file: 'reverb-repository-generation.schema.json', schema: repositoryGenerationSchema },
  { file: 'reverb-pull-request-overlay.schema.json', schema: overlaySchema },
  { file: 'reverb-workspace-registry.schema.json', schema: registrySnapshotSchema },
  { file: 'reverb-adapter-manifest.schema.json', schema: adapterManifestSchema },
  { file: 'reverb-adapter-extraction.schema.json', schema: adapterExtractionSchema },
  { file: 'reverb-evidence-edge.schema.json', schema: evidenceEdgeSchema },
  { file: 'reverb-analysis-result.schema.json', schema: analysisResultSchema },
  { file: 'reverb-review-event.schema.json', schema: reviewEventSchema },
  { file: 'reverb-suppression-rule.schema.json', schema: suppressionRuleSchema },
  { file: 'reverb-impact-case.schema.json', schema: impactCaseSchema },
  { file: 'reverb-corpus-manifest.schema.json', schema: corpusManifestSchema },
  { file: 'reverb-evaluation-report.schema.json', schema: evaluationReportSchema },
  { file: 'reverb-policy-simulation.schema.json', schema: policySimulationSchema },
  { file: 'reverb-promotion-record.schema.json', schema: promotionRecordSchema },
  {
    file: 'reverb-finding-disclosure-projection.schema.json',
    schema: findingDisclosureProjectionSchema,
  },
  { file: 'reverb-github-check-projection.schema.json', schema: githubCheckProjectionSchema },
]);
